Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/16/2022
Var
// Seção de Declarações das variáveis 
a, b, c, p : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
leia (a, b)
c <- 1
p <- 1
enquanto (c <= b) faça
p <- p*a
c <- c+1
fimenquanto
escreval (p)


Fimalgoritmo