Algoritmo "enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/18/2022
Var
// Seção de Declarações das variáveis 
n1 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n1 <- 0.1

   enquanto n1 < 1 faça
            escreval (n1)
            n1 <- n1+0.01
   fimenquanto
   
Fimalgoritmo