Algoritmo "para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/18/2022
Var
// Seção de Declarações das variáveis 
       n1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para n1 de 1 ate 10 passo 2 faça
escreval (n1)
fimpara


Fimalgoritmo